macro(system_info)
    message("=========================== System Info =========================== ")
    if (WIN32)
        message("Running on Windows")
    elseif(LINUX)
        message("Running on Linux")
    elseif(UNIX)  
        message("Running on Mac") 
    endif()
    
    message("-----------> Using ${CMAKE_CXX_COMPILER_ID} compilator")
    message("-----------> Compiler flags: ${CMAKE_CXX_FLAGS}")
    message("-----------> Compiler debug flags:  ${CMAKE_CXX_FLAGS_DEBUG}")
    message("-----------> Compiler release flags:  ${CMAKE_CXX_FLAGS_RELEASE}")
    message("-----------> Compiler configuration types ${CMAKE_CONFIGURATION_TYPES}")
endmacro()

macro(setup_conan HOST_PROFILE BUILD_PROFILE)
    set(CMAKE_CONAN_PATH "${CMAKE_BINARY_DIR}/conan_provider.cmake")

    if (NOT EXISTS ${CMAKE_CONAN_PATH}) 
        message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan/blob/develop2/conan_provider.cmake")
        file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/refs/heads/develop2/conan_provider.cmake" "${CMAKE_CONAN_PATH}")
    endif()

    set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES ${CMAKE_CONAN_PATH})
    set(CONAN_HOST_PROFILE ${HOST_PROFILE})
    set(CONAN_BUILD_PROFILE ${BUILD_PROFILE})
endmacro()